version: 2
jobs:
  test_plugin:
    docker:
    - image: circleci/node:10
    working_directory: ~/plugin
    steps:
    - checkout
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Run Toolkit Build
        command: npx grafana-toolkit plugin:test
    - save_cache:
        paths:
        - node_modules
        key: yarn-packages-{{ checksum "yarn.lock" }}
  build_plugin:
    docker:
    - image: circleci/node:10
    working_directory: ~/plugin
    steps:
    - checkout
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Run Toolkit Build
        command: npx grafana-toolkit plugin:dev
    - save_cache:
        paths:
        - node_modules
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - persist_to_workspace:
        root: .
        paths:
        - dist
workflows:
  version: 2
  plugin_workflow:
    jobs:
    - test_plugin
    - build_plugin
